//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileKeeperDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileKeeperDesktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Universal symmetric cyptoalgorythm. Encrypts and decrypts file of any type with a key..
        /// </summary>
        public static string AESDescription {
            get {
                return ResourceManager.GetString("AESDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AES.
        /// </summary>
        public static string AESModeName {
            get {
                return ResourceManager.GetString("AESModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One of most primitive ciphers. Can encrypt only text data. Not recommended to keep pivate files..
        /// </summary>
        public static string CaesarDescription {
            get {
                return ResourceManager.GetString("CaesarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Caesar Cipher.
        /// </summary>
        public static string CaesarModeName {
            get {
                return ResourceManager.GetString("CaesarModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Here will be a short description of this cipher.
        /// </summary>
        public static string CipherModeDefaultText {
            get {
                return ResourceManager.GetString("CipherModeDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] cryptography {
            get {
                object obj = ResourceManager.GetObject("cryptography", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What do you want to do with your files today?.
        /// </summary>
        public static string CryptographyRequestLabel {
            get {
                return ResourceManager.GetString("CryptographyRequestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔓Decrypt File.
        /// </summary>
        public static string DecryptFileText {
            get {
                return ResourceManager.GetString("DecryptFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔒Encrypt file.
        /// </summary>
        public static string EncryptFileText {
            get {
                return ResourceManager.GetString("EncryptFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encryption Mode.
        /// </summary>
        public static string EncryptionModeTitle {
            get {
                return ResourceManager.GetString("EncryptionModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encrypt/Decrypt file.
        /// </summary>
        public static string EncryptionOrDecryptionModeLabelText {
            get {
                return ResourceManager.GetString("EncryptionOrDecryptionModeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ecnryption.
        /// </summary>
        public static string EncryptionPageShellTitle {
            get {
                return ResourceManager.GetString("EncryptionPageShellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string FileErrorTitle {
            get {
                return ResourceManager.GetString("FileErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File has been successfully loaded!.
        /// </summary>
        public static string FileLoaded {
            get {
                return ResourceManager.GetString("FileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File receiving progress:.
        /// </summary>
        public static string FileProgress {
            get {
                return ResourceManager.GetString("FileProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error while file receiving. Please, try again..
        /// </summary>
        public static string FileReceivingError {
            get {
                return ResourceManager.GetString("FileReceivingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your code will be reset and connection will be closed at.
        /// </summary>
        public static string FileResetWarning {
            get {
                return ResourceManager.GetString("FileResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File has been successfully saved!.
        /// </summary>
        public static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the file.
        /// </summary>
        public static string FileSelectionTitle {
            get {
                return ResourceManager.GetString("FileSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error while file sending.
        /// </summary>
        public static string FileSendingErrorText {
            get {
                return ResourceManager.GetString("FileSendingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save open key.
        /// </summary>
        public static string GenerateOpenKey {
            get {
                return ResourceManager.GetString("GenerateOpenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save private key.
        /// </summary>
        public static string GeneratePrivateKey {
            get {
                return ResourceManager.GetString("GeneratePrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string HomePageShellTitle {
            get {
                return ResourceManager.GetString("HomePageShellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write your encryption key here….
        /// </summary>
        public static string KeyPlaceholderText {
            get {
                return ResourceManager.GetString("KeyPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load open key.
        /// </summary>
        public static string LoadOpenKey {
            get {
                return ResourceManager.GetString("LoadOpenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load private key.
        /// </summary>
        public static string LoadPrivateKey {
            get {
                return ResourceManager.GetString("LoadPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Homepage.
        /// </summary>
        public static string MenuTitle1 {
            get {
                return ResourceManager.GetString("MenuTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encrypt Files.
        /// </summary>
        public static string MenuTitle2 {
            get {
                return ResourceManager.GetString("MenuTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transfer Files.
        /// </summary>
        public static string MenuTitle3 {
            get {
                return ResourceManager.GetString("MenuTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transfer between PC.
        /// </summary>
        public static string MenuTitle4 {
            get {
                return ResourceManager.GetString("MenuTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scan a QR-code to connect….
        /// </summary>
        public static string RecieveFilePageText {
            get {
                return ResourceManager.GetString("RecieveFilePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Receive file.
        /// </summary>
        public static string RecieveFilePageTitle {
            get {
                return ResourceManager.GetString("RecieveFilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An asymmmetric cipher that generates open and private keys. Open key is needed to encrypt the file, private decrypts it. This app can generate key pair to save them into files. You can encrypt file with private key because it contains full data of a key..
        /// </summary>
        public static string RSADescription {
            get {
                return ResourceManager.GetString("RSADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RSA.
        /// </summary>
        public static string RSAModeName {
            get {
                return ResourceManager.GetString("RSAModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Security.
        /// </summary>
        public static string SecurePageShellTitle {
            get {
                return ResourceManager.GetString("SecurePageShellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select current cypher mode:.
        /// </summary>
        public static string SelectCypherText {
            get {
                return ResourceManager.GetString("SelectCypherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a file to send….
        /// </summary>
        public static string SendFilePageText {
            get {
                return ResourceManager.GetString("SendFilePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send file.
        /// </summary>
        public static string SendFilePageTitle {
            get {
                return ResourceManager.GetString("SendFilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This app needs to access to external storage because of its functionality: file encryption system encrypts files in specified location. .
        /// </summary>
        public static string StorageWritePromptText {
            get {
                return ResourceManager.GetString("StorageWritePromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application needs to get a permission.
        /// </summary>
        public static string StorageWritePromptTitle {
            get {
                return ResourceManager.GetString("StorageWritePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully done!.
        /// </summary>
        public static string SuccessResult {
            get {
                return ResourceManager.GetString("SuccessResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transfer.
        /// </summary>
        public static string TransferPageShellTitle {
            get {
                return ResourceManager.GetString("TransferPageShellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can encrypt only text data. Requires a key to encrypt and decrypt..
        /// </summary>
        public static string VigenereDescription {
            get {
                return ResourceManager.GetString("VigenereDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vigenere Cipher.
        /// </summary>
        public static string VigenereModeName {
            get {
                return ResourceManager.GetString("VigenereModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to FileKeeper Desktop!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FileKeeper is an application which can help you protect your personal data. You can encrypt files to prevent them from unauthorized access.
        /// </summary>
        public static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
    }
}
