//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileKeeperMAUI {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileKeeperMAUI.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Universal symmetric cyptoalgorythm. Encrypts and decrypts file of any type with a key..
        /// </summary>
        internal static string AESDescription {
            get {
                return ResourceManager.GetString("AESDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AES.
        /// </summary>
        internal static string AESModeName {
            get {
                return ResourceManager.GetString("AESModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One of most primitive ciphers. Can encrypt only text data. Not recommended to keep pivate files..
        /// </summary>
        internal static string CaesarDescription {
            get {
                return ResourceManager.GetString("CaesarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Caesar Cipher.
        /// </summary>
        internal static string CaesarModeName {
            get {
                return ResourceManager.GetString("CaesarModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Here will be a short description of this cipher.
        /// </summary>
        internal static string CipherModeDefaultText {
            get {
                return ResourceManager.GetString("CipherModeDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What do you want to do with your files today?.
        /// </summary>
        internal static string CryptographyRequestLabel {
            get {
                return ResourceManager.GetString("CryptographyRequestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔓Decrypt File.
        /// </summary>
        internal static string DecryptFileText {
            get {
                return ResourceManager.GetString("DecryptFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔒Encrypt file.
        /// </summary>
        internal static string EncryptFileText {
            get {
                return ResourceManager.GetString("EncryptFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encryption Mode.
        /// </summary>
        internal static string EncryptionModeTitle {
            get {
                return ResourceManager.GetString("EncryptionModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encrypt/Decrypt file.
        /// </summary>
        internal static string EncryptionOrDecryptionModeLabelText {
            get {
                return ResourceManager.GetString("EncryptionOrDecryptionModeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ecnryption.
        /// </summary>
        internal static string EncryptionPageShellTitle {
            get {
                return ResourceManager.GetString("EncryptionPageShellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string FileErrorTitle {
            get {
                return ResourceManager.GetString("FileErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File has been successfully loaded!.
        /// </summary>
        internal static string FileLoaded {
            get {
                return ResourceManager.GetString("FileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File receiving progress:.
        /// </summary>
        internal static string FileProgress {
            get {
                return ResourceManager.GetString("FileProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error while file receiving. Please, try again..
        /// </summary>
        internal static string FileReceivingError {
            get {
                return ResourceManager.GetString("FileReceivingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your code will be reset and connection will be closed at.
        /// </summary>
        internal static string FileResetWarning {
            get {
                return ResourceManager.GetString("FileResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File has been successfully saved!.
        /// </summary>
        internal static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the file.
        /// </summary>
        internal static string FileSelectionTitle {
            get {
                return ResourceManager.GetString("FileSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error while file sending.
        /// </summary>
        internal static string FileSendingErrorText {
            get {
                return ResourceManager.GetString("FileSendingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save open key.
        /// </summary>
        internal static string GenerateOpenKey {
            get {
                return ResourceManager.GetString("GenerateOpenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save private key.
        /// </summary>
        internal static string GeneratePrivateKey {
            get {
                return ResourceManager.GetString("GeneratePrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        internal static string HomePageShellTitle {
            get {
                return ResourceManager.GetString("HomePageShellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write your encryption key here….
        /// </summary>
        internal static string KeyPlaceholderText {
            get {
                return ResourceManager.GetString("KeyPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load open key.
        /// </summary>
        internal static string LoadOpenKey {
            get {
                return ResourceManager.GetString("LoadOpenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load private key.
        /// </summary>
        internal static string LoadPrivateKey {
            get {
                return ResourceManager.GetString("LoadPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scan a QR-code to connect….
        /// </summary>
        internal static string RecieveFilePageText {
            get {
                return ResourceManager.GetString("RecieveFilePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Receive file.
        /// </summary>
        internal static string RecieveFilePageTitle {
            get {
                return ResourceManager.GetString("RecieveFilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An asymmmetric cipher that generates open and private keys. Open key is needed to encrypt the file, private decrypts it. This app can generate key pair to save them into files. You can encrypt file with private key because it contains full data of a key..
        /// </summary>
        internal static string RSADescription {
            get {
                return ResourceManager.GetString("RSADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RSA.
        /// </summary>
        internal static string RSAModeName {
            get {
                return ResourceManager.GetString("RSAModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scan a QR-code....
        /// </summary>
        internal static string ScanQRText {
            get {
                return ResourceManager.GetString("ScanQRText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Security.
        /// </summary>
        internal static string SecurePageShellTitle {
            get {
                return ResourceManager.GetString("SecurePageShellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a file to send….
        /// </summary>
        internal static string SendFilePageText {
            get {
                return ResourceManager.GetString("SendFilePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send file.
        /// </summary>
        internal static string SendFilePageTitle {
            get {
                return ResourceManager.GetString("SendFilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This app needs to access to external storage because of its functionality: file encryption system encrypts files in specified location. .
        /// </summary>
        internal static string StorageWritePromptText {
            get {
                return ResourceManager.GetString("StorageWritePromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application needs to get a permission.
        /// </summary>
        internal static string StorageWritePromptTitle {
            get {
                return ResourceManager.GetString("StorageWritePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully done!.
        /// </summary>
        internal static string SuccessResult {
            get {
                return ResourceManager.GetString("SuccessResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transfer.
        /// </summary>
        internal static string TransferPageShellTitle {
            get {
                return ResourceManager.GetString("TransferPageShellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can encrypt only text data. Requires a key to encrypt and decrypt..
        /// </summary>
        internal static string VigenereDescription {
            get {
                return ResourceManager.GetString("VigenereDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vigenere Cipher.
        /// </summary>
        internal static string VigenereModeName {
            get {
                return ResourceManager.GetString("VigenereModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to FileKeeper!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FileKeeper is an application which can help you protect your personal data. You can encrypt files to prevent them from unauthorized access.
        /// </summary>
        internal static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
    }
}
